### ISSUE TITLE
Top and Footer contentcollections are not defined as ChildNodes of Page configuration

### ISSUE THREAD

**Issue by dimaip** [million12/M12.FoundationSite#1]
If we need those contentCollections to be there, they should be defined in nodeType configuration. However as they are needed only for some layouts, it's best to use separate nodetypes rather than layouts, so they would not be visible where they are not active.

**Comment by ryzy** [comment]
Resolved by c55c77892d370e9f4b4994074ca25cc62d129179  and ec569887f684b44de252f2cd42f7266ee3b60a97.
